import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from 'sonner';

import { ConvexClientProvider } from '@/components/providers/convex-client.provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider signInUrl='/sign-in' signUpUrl='/sign-up'
          appearance={{
            variables: {
              colorPrimary: '#2489EE',
            },
            layout: {
              socialButtonsPlacement: 'bottom',
              shimmer: true,
            },
            captcha: {
              theme: 'auto',
              size: 'flexible',
            },
            elements: {
              card: '!bg-transparent !shadow-none',
              cardBox: '!bg-transparent !shadow-none',
              input: '!p-2.5',
              formButtonPrimary: '!p-2.5',
              socialButtonsBlockButton: '!p-2.5',
            },
          }}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </ClerkProvider>
        <Toaster />
      </body>
    </html>
  );
}
