#!/bin/sh

echo '👷‍♂️ Starting pre-commit checks...'


# bun run format || {
#   echo '❌ Formatting failed.'
#   exit 1
# }

echo '🧹 Linting ...'
bun run lint || {
  echo '❌ Linting failed. Please fix the errors before committing.'
  exit 1
}

echo '✅ All pre-commit checks passed. Proceeding with commit. 🚀'
